Update APIM-Extract-APIs-and-Artifacts.yml

diff --git a/.github/workflows/APIM-Extract-APIs-and-Artifacts.yml b/.github/workflows/APIM-Extract-APIs-and-Artifacts.yml
--- a/.github/workflows/APIM-Extract-APIs-and-Artifacts.yml
+++ b/.github/workflows/APIM-Extract-APIs-and-Artifacts.yml
@@ -87,13 +87,25 @@ jobs:
       #      This is where you add the absolute path to the configuration file.                   #
       #############################################################################################
       - run: |
-          if ("${{inputs.USE_CONFIG_FILE}}" -eq "apisTeam1" )
-          {
-            "CONFIGURATION_YAML_PATH=${{ GITHUB.WORKSPACE }}/src/apisTeam1.yaml" >> $env:GITHUB_ENV
-          }
-          elseif ("${{inputs.USE_CONFIG_FILE}}" -eq "apisTeam2" )
-          {
-            "CONFIGURATION_YAML_PATH=${{ GITHUB.WORKSPACE }}/src/apisTeam2.yaml" >> $env:GITHUB_ENV
+          echo "USE_CONFIG_FILE=${{ github.event.inputs.USE_CONFIG_FILE }}" >> $env:GITHUB_ENV
+          if (${{ github.event.inputs.USE_CONFIG_FILE }} -eq "true") {
+            if ([string]::IsNullOrEmpty("${{ github.event.inputs.CONFIG_FILE_NAME }}")) {
+              Write-Error "Error: CONFIG_FILE_NAME must be provided when USE_CONFIG_FILE is selected."
+              exit 1
+            } else {
+              echo "CONFIG_FILE_NAME=${{ github.event.inputs.CONFIG_FILE_NAME }}" >> $env:GITHUB_ENV
+
+              if ("${{ github.event.inputs.CONFIG_FILE_NAME }}" -eq "config1") {
+                echo "CONFIGURATION_YAML_PATH=${{ github.workspace }}/src/apisTeam1.yaml" >> $env:GITHUB_ENV
+              } elseif ("${{ github.event.inputs.CONFIG_FILE_NAME }}" -eq "config2") {
+                echo "CONFIGURATION_YAML_PATH=${{ github.workspace }}/src/apisTeam2.yaml" >> $env:GITHUB_ENV
+              } elseif ("${{ github.event.inputs.CONFIG_FILE_NAME }}" -eq "config3") {
+                echo "CONFIGURATION_YAML_PATH=${{ github.workspace }}/src/apisTeam3.yaml" >> $env:GITHUB_ENV
+              }
+            }
+          } else {
+            echo "CONFIG_FILE_NAME=not_selected" >> $env:GITHUB_ENV
+            echo "CONFIGURATION_YAML_PATH=not_applicable" >> $env:GITHUB_ENV
           }
         shell: pwsh
     
